name: ScrippsPierSCS
channels:
  - conda-forge  
  - defaults
  - conda-forge/label/broken
dependencies:
  - pandas
  - numpy
  - matplotlib
  - plotly
  - requests
  - bs4
  - os
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dash
